BlowOut/Models/Instrument.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using BlowOut.Models;

namespace BlowOut.Models
{
    [Table("Instrument")]
    public class Instrument
    {
        [Key]
        public int iInstrumentID { get; set; }

        [DisplayName("Instrument Name")]
        public string sInstrumentDesc { get; set; }

        [DisplayName("Instrument Type")]
        public bool bInstrumentType  { get; set; }

        [DisplayName("Price")]
        public decimal dInstrumentPrice { get; set; }

        public int? iCustomerID { get; set; }

        public string sImageFileName { get; set; }

    }
}

BlowOut/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class CustomersController : Controller
    {
        private BlowOutContext db = new BlowOutContext();
        public decimal price = 0;

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        
        // GET: Customers/Create
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iCustomerID,sCustFirstName,sCustLastName,sCustAddress,sCustState,sCustCity,iCustZip,cCustPhone,cCustEmail")] Customer customer, int id)
        {
            if (ModelState.IsValid)
            {
                //First we need to create a new Instrument object to point to the instrument we clicked on in the InstrumentsController.
                Instrument instrument = db.Instruments.Find(id);

                //Now we add the customer to our database
                db.Customers.Add(customer);

                //db.Entry(Instrument).State = EntityState.Modified;
                db.SaveChanges();


                //then we assign our instrument's customerID to the customer's ID we just created.
                db.Database.ExecuteSqlCommand(
                    "UPDATE Instrument " +
                    "SET iCustomerID = " + customer.iCustomerID +
                    " WHERE iInstrumentID = " + instrument.iInstrumentID);
                

                
                //Go to our summary action.
                return RedirectToAction("Summary", new { CustomerID = customer.iCustomerID, InstrumentID = instrument.iInstrumentID });
            }

            return View(customer);
        }

        public ActionResult Summary(int CustomerID, int InstrumentID)
        {
            Customer customer = db.Customers.Find(CustomerID);
            Instrument instrument = db.Instruments.Find(InstrumentID);

            //calculate the total price after 18 months
            price = instrument.dInstrumentPrice * 18;


            ViewBag.customer = customer;
            ViewBag.instrument = instrument;
            ViewBag.totalprice = price;

            return View();

        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iCustomerID,sCustFirstName,sCustLastName,sCustAddress,sCustState,sCustCity,iCustZip,cCustPhone,cCustEmail")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Controllers/InstrumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class InstrumentsController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        // GET: Instruments
        public ActionResult Index()
        {
            return View(db.Instruments.ToList());
        }

        // GET: Instruments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // GET: Instruments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Instruments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iInstrumentID,sInstrumentDesc,bInstrumentType,dInstrumentPrice,iCustomerID,sImageFileName")] Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                db.Instruments.Add(instrument);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(instrument);
        }

        // GET: Instruments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // POST: Instruments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iInstrumentID,sInstrumentDesc,bInstrumentType,dInstrumentPrice,iCustomerID,sImageFileName")] Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instrument).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(instrument);
        }

        // GET: Instruments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // POST: Instruments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instrument instrument = db.Instruments.Find(id);
            db.Instruments.Remove(instrument);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Controllers/RentalsController.cs
using BlowOut.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;

namespace BlowOut.Controllers
{
    public class RentalsController : Controller
    {
        private BlowOutContext db = new BlowOutContext();
        public IEnumerable<Instrument> listofRentals;
        public CustInts newRental = new CustInts();
        public List<CustInts> allinfo = new List<CustInts>();

        public string instName = "";
        public int instNew = 0;
        public int instOld = 0;
        // GET: Rentals
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult Detail(string sInstrumentDesc)
        {
            var instrument = new Instrument();

            //instrument = db.Instruments.FirstOrDefault(model => model.sInstrumentDesc = );

                //db.Database.SqlQuery<Instrument>(
                //    "SELECT " +
                //        "sInstrumentDesc, sImageFileName" +
                //    " FROM " +
                //        "Instrument" +
                //    " WHERE " +
                //        "sInstrumentDesc = '" + sInstrumentDesc + "' AND bInstrumentType = 0;"
                //    );

            return View(instrument);
        }

        public ActionResult listRentals()
        {

            listofRentals = db.Database.SqlQuery<Instrument>(
                "SELECT * " +
                "FROM Instrument " +
                "WHERE iCustomerID IS NOT NULL").ToList();

            foreach (var item in listofRentals)
            {
                newRental.instruments = item;
                newRental.customers = db.Customers.Find(item.iCustomerID);
                allinfo.Add(newRental);

            }

            return View(allinfo);
        }

        
            
        
    }
}

BlowOut/Views/Instruments/Create.cshtml
@model BlowOut.Models.Instrument

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instrument</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sInstrumentDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sInstrumentDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sInstrumentDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bInstrumentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.bInstrumentType)
                    @Html.ValidationMessageFor(model => model.bInstrumentType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dInstrumentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dInstrumentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dInstrumentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iCustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sImageFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sImageFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sImageFileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlowOut/Views/Instruments/Delete.cshtml
@model BlowOut.Models.Instrument

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instrument</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sInstrumentDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sInstrumentDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bInstrumentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bInstrumentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dInstrumentPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dInstrumentPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iCustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iCustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sImageFileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sImageFileName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlowOut/Views/Instruments/Details.cshtml
@model BlowOut.Models.Instrument
@{
    ViewBag.Title = "TrumpetDet";
}

<head>
    <link rel="stylesheet" href="~/Content/Newstyles.css" />
</head>

<h2>@Html.DisplayFor(model => model.sInstrumentDesc) Details</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <img class="pics" src="~/Content/Images/ + @Html.DisplayFor(model => model.sInstrumentDesc)" />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            @Html.ActionLink("Show New Price", "NewUsedPrice", "Rentals", new { stype = "New", instrumentID = "Trumpet" }, null)
        </div>
        <div class="col-lg-6">
            @Html.ActionLink("Show Used Price", "NewUsedPrice", "Rentals", new { stype = "Used", instrumentID = "Trumpet" }, null)
        </div>
    </div>
</div>

BlowOut/Views/Instruments/Edit.cshtml
@model BlowOut.Models.Instrument

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instrument</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.iInstrumentID)

        <div class="form-group">
            @Html.LabelFor(model => model.sInstrumentDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sInstrumentDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sInstrumentDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bInstrumentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.bInstrumentType)
                    @Html.ValidationMessageFor(model => model.bInstrumentType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dInstrumentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dInstrumentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dInstrumentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iCustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sImageFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sImageFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sImageFileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlowOut/Views/Instruments/Index.cshtml
@model IEnumerable<BlowOut.Models.Instrument>

@{
    ViewBag.Title = "Index";
}

<head>
    <link rel="stylesheet" href="~/Content/Newstyles.css" />
</head>

<h2>Index</h2>

<div class="container">
    <div class="row" style="padding-bottom:20px">
        @foreach (var item in Model)
        {

            @Html.DisplayFor(modelitem => item.sInstrumentDesc)
            <br />
            <div class="col-lg-4 btn">
                <a href="@Url.Action("Create", "Customers", new {id= item.iInstrumentID})">
                    <img class="card-body pics" src="../../Content/Images/@Html.DisplayFor(modelitem => item.sImageFileName)" />
                </a>
            </div>
        }
    </div>
</div>