BlowOut/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlowOut.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        [Route("Contact/index")]
        [Route("Contact")]
        public ActionResult Index()
        {
            ViewBag.support = "Please call Support at ";
            ViewBag.support += "<u><strong>801-555-1212</strong></u>";
            ViewBag.support += ". Thank you!";
            return View();
        }

        //These routes take precedence over the ones in the RouteConfig.cs
        //You only need one of these. Either in the Controller like this one or in the RouteConfig.cs
        //This route is attribute routing and RouteConfig.cs is conventional routing
        [Route("Contact/Email/{name:string}/{email:string}")]
        public ActionResult Email(string name, string email)
        {
            ViewBag.thanks = "Thanks " + name + ". The company will send an email to " + email;
            return View();
        }
    }
}

BlowOut/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class HomeController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Rentals()
        {
            return View(db.Instruments.ToList());
        }
    }
}

BlowOut/Controllers/InstrumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class InstrumentsController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        // GET: Instruments
        public ActionResult Index()
        {
            return View(db.Instruments.ToList());
        }

        // GET: Instruments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // GET: Instruments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Instruments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "iInstrumentID,sInstrumentDesc,bInstrumentType,dInstrumentPrice,iCustomerID,sImageFileName")] Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                db.Instruments.Add(instrument);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(instrument);
        }

        // GET: Instruments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // POST: Instruments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "iInstrumentID,sInstrumentDesc,bInstrumentType,dInstrumentPrice,iCustomerID,sImageFileName")] Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instrument).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(instrument);
        }

        // GET: Instruments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instrument instrument = db.Instruments.Find(id);
            if (instrument == null)
            {
                return HttpNotFound();
            }
            return View(instrument);
        }

        // POST: Instruments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instrument instrument = db.Instruments.Find(id);
            db.Instruments.Remove(instrument);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="jumbotron" style="background-image: url('../../Content/Images/trumpetstore.jpg'); background-size: cover">
    <div>
        <h1>About</h1>
        <p class="lead">Our Mission and Our History</p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>History</h2>
        <p>
            BlowOut Instrument Rentals was founded by Jamal Lewis in December of 2005.
            Jamal comes from a long line of musicians in his family even though his family was very poor growing up.
            Jamal had a dream of opening up a small instrument shop to better provide for him and his family.
            He also wanted to make sure that less fortunate musicians had a way to access instruments and use them for little to no cost.
            In order to accomplish this noble desire, Jamal created a program where musicians could come to his store anytime during business hours
            to use an instrument and recieve lessons from volunteer teachers.
        </p>
        <p>
            The first shop the Jamal opened was located in Chicago, Illinois in 2005. Since that date he has sold and rented thousands of instruments.
            He has served thousand of individuals through his instrument lending program. Currently Jamal owns 5 other shops throughout the state of Illinois.
        </p>
        <h2>Mission</h2>
        <p>
            BlowOut's mission is to change the lives of muscians by providing all with high quality instruments through sales, leases, and lending.
        </p>
    </div>
    <div class="col-md-6">
        <img src="~/Content/Images/BlowOutOwner1.jpg" style="height: 100%; width: 100%; object-fit: contain" />
    </div>
</div>
<!--The about link should display the About view (you need to code this)
    describing the history and mission of the company along with a picture
    of the founder (you can choose any picture).-->

BlowOut/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BlowOut/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Blow Out!";
}

<div class="jumbotron container">
    <div class="row">
        <div class="col-lg-6">
            <h1>Welcome to Blow Out</h1>
            <p class="lead">We blow our competitors out of the water</p>
            <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
        </div>
        <!--This will be the picture-->
        <div class="col-lg-6">
            <img src="~/Content/Images/audio-e-guitars-guitars-music-6966.jpg" class="img-fluid" style="max-width: 100%; height:auto" />
        </div>
    </div>
    
</div>

<div class="container-fluid">
    <div class="row">
        <!-- Then we will have an explanation-->
        <div class="col-md-5">
            <div class="row" style="padding:20px">
                Here at BlowOut instrument rentals we allow for users of all skill levels to rent new and used instruments
            </div>
            <div class="row" style="padding:20px">
                <em>"It's easy to play any musical instrument: all you have to do is touch the right key at the right time and the instrument will play itself”.</em> <br /> - Johann Sebastian Bach
            </div>
        </div>
        <!--Then there will be the three buttons. Rentals, About, and Contact-->
        <div class="col-md-7">
            
            <button class="btn-lg" style="padding:15px">@Html.ActionLink("Rentals", "Index", "Instruments")</button><br /><br />
            <button class="btn-lg" style="padding:15px">@Html.ActionLink("About", "Index", "Home")</button><br /><br />
            <button class="btn-lg" style="padding:15px">@Html.ActionLink("Contact", "Index", "Home")</button>
        </div>
    </div>
</div>